nodes:
  - name: "BitSong"
    api_url: "https://api.bitsong.chaintools.tech:443/"
    host: "htz-host-01"
    main_denom: "ubtsg"
    validators:
      - validator_id: "bitsongvaloper1x2slrjfmgxq7qx3xwmsjue73t5ynmwy7jgpdtr"
    wallets:
      - { address: "bitsong1vp9xldhdmjfmnwel7nl6tgy8numduq08qm4jpm", type: "relayer" }
      - { address: "bitsong1x2slrjfmgxq7qx3xwmsjue73t5ynmwy7nvaym7", type: "validator" }
  - name: "Sentinel"
    api_url: "https://api.sentinel.chaintools.tech:443/"
    host: "ovh-host-08"
    main_denom: "udvpn"
    validators:
      - validator_id: "sentvaloper1p3u583ms39yrz7dkcetxdkn4sj66sjau4250pu"
    wallets:
      - address: "sent1p3u583ms39yrz7dkcetxdkn4sj66sjau20tzw4"
      - { address: "sent1vp9xldhdmjfmnwel7nl6tgy8numduq08hf3r8m", type: "relayer" }
